# Site settings
title: "Parthia London"
email: hello@parthialondon.com
description: "We create digital content. From soup to nuts."
url: "http://parthialondon.com"
baseurl: ""

defaults:
  - scope:
      path: ""
    values:
      layout: "base"
  - scope:
      path: "pages"
    values:
      layout: "page"

# Build settings
exclude: ['Gruntfile.js', 'node_modules', 'package.json', 'readme.md']
markdown: kramdown
permalink: pretty
