# Site settings
title: "Parthia London"
email: info@parthiaproductions.com
email_greta: greta@parthiaproductions.com
description: "We create digital content. From soup to nuts"
url: "http://parthialondon.com"
baseurl: ""

defaults:
  - scope:
      path: "pages"
    values:
      layout: "page"

# Build settings
markdown: kramdown
permalink: pretty
