# Site settings
title: "Parthia London"
email: info@parthialondon.com
description: "Write an awesome description for your new site here."
url: "http://parthialondon.com"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty
